dist: xenial
branches:
  only:
  - master
language: node_js
services:
  - docker
node_js: lts/*
cache: npm
install:
- npm install
- npm run examples
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: visual-test
      script:
        - npm install -g backstopjs
        - npm run visual-test
