version: "3.7"
services:
  static:
    image: nginx:alpine
    ports:
      - "3333:3333"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webpubViewer.pem:/etc/nginx/webpubViewer.pem
      - ./examples/static:/usr/share/nginx/html
networks:
  default:
    name: webpub-viewer